version: '3.8'

networks:
  backend:
    driver: bridge

services:

  recruit:
    container_name: recruit
    image: recruit/php
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/srv:cached
    tty: true
    networks:
      - backend
    deploy:
      resources:
        limits:
          memory: 512M
